### PR TITLE
fix: format readme table and fix null pointer issue

### PR DESCRIPTION
**Pull request by Joel-hanson**
# Description

- This PR trys to fix an issue with the converter that is causing the whole pipeline to fail. The issue is that when calling the method `addArrayElements` the source.getArray(field) call fails with null pointer exceptiong. This is happening because for a optional field (`phones`) in `source`. This can be easily recreated with the `loosehangerjeans` source connector.

```json
{
    "name": "kafka-datagen-xml",
    "config": {
        "connector.class": "com.ibm.eventautomation.demos.loosehangerjeans.DatagenSourceConnector",
        "tasks.max": "1",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "key.converter.schemas.enable": "true",
        "value.converter": "com.ibm.eventstreams.kafkaconnect.plugins.xml.XmlConverter",
        "value.converter.schemas.enable": "true",
        "value.converter.xml.doc.flat.enable": "true"
    }
}
```

- This PR also formatts the tables in the readme.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- [ ] E2E
- [x] Unit Test
- [ ] Integration Test

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by dalelane — CHANGES_REQUESTED** [review]
If we identify a type of data that the converter fails with, the first step is to add tests for that type of data. 

This has several benefits:
- it will give us confidence that our fix really addresses the problem
- it will identify if this bug has impacts in other areas
- it will prevent us accidentally regressing the fix in future changes

I'll see if your fork will let me add an example test.

**Comment by dalelane** [comment]
The new tests are failing - this is highlighting that the problems with handling optional arrays are broader than the fix currently in the PR. I'll have a try at fixing it.

**Review by dalelane — CHANGES_REQUESTED** [review]
It still needs a bump to the version number. I'll leave you to do that.

**Review by dalelane — APPROVED** [review]
I think we're good - thanks very much 👍

**Comment by Joel-hanson** [comment]
Thanks

**Pull request merged**
